### ISSUE TITLE
What if the path to editor has spaces?

### ISSUE THREAD

**Issue by dufferzafar** [laurent22/massren#19]
I'm using Windows and tried to set the editor using this command:

`massren --config editor "F:\Sublime Text 3\sublime_text.exe -n -w"`

The command executes successfully, but when I try to launch massren, the following error occurs:

```
massren: Waiting for file list to be saved... (Press Ctrl + C to abort)
massren: exec: "F:\\Sublime": file does not exist
massren: Run 'massren --help' for usage
```

I'm guessing just wrapping the path in quotes [here](https://github.com/laurent22/massren/blob/master/main.go#L185) should solve the problem?

**Comment by hashhar** [comment]
Still not fixed.
What do we do to handle flags. Mostly flags start with either dashes or slahes and will have a space preceding them.
`C:\Program Files\VSCode.exe -g -x` or `C:\Program Files\VSCode.exe /g /x` should be handled.

Can we split only when we find both a space and a - or / or --?

**Comment by hashhar** [comment]
This works but removes the leading -, --, and /.

```go
if (strings.Contains(editorCmd, " --") {
    pieces := strings.Split(editorCmd, " --")
} elseif (strings.Contains(editorCmd, " -") {
   pieces := strings.Split(editorCmd, " -")
} else {
  pieces := string.Split(editorCmd, " ")
}
pieces = append(pieces, filePath)
```

**Comment by laurent22** [comment]
Hmm, yes that seems quite complex because it indeed looks like we should parse the flags if we want to support this properly.

Ideally, I think the test cases we should be able to handle are:

    subl
    /usr/bin/vim -f
    "F:\Sublime Text 3\sublime_text.exe" -n -w
    subl -w --command "something with spaces"
    notepad /PT

Case that we *do not* need to handle:

    F:\Sublime Text 3\sublime_text.exe -n -w

Because this is not a valid command since there should be quotes around the executable path and name.

Maybe a simple solution would to use a dedicated flag parser like [go-flags](https://github.com/jessevdk/go-flags)?

**Comment by hashhar** [comment]
Go-flag looks well suited, we can even parse from strings.

**Comment by hashhar** [comment]
I'll add those testcases to a separate test file for now so that they don't hinder with the Travis CI builds.

**Comment by hashhar** [comment]
I got this going now. The code is working locally on the testcases. I dont have internet right now (on my mobile currently). I'll get it through Travis and submit a PR once i get hold of internet.

**Comment by laurent22** [comment]
Thanks, I've moved the parsing code to a function so that we can unit test it, and added some the unit tests for it in `Test_parseEditorCommand`. At the moment, some of the tests are failing due to quote and space issues. Basically, the tests check that the function returns the executable path and the arguments. For example, they expect this:

    "/usr/bin/vim -v -i"

is going to be parsed into:

    executable: /usr/bin/vim
    args (a slice): [ -v, -i ]

and:

    subl -w --command "something with spaces"

into:

    executable: subl
    args: [ -w, --command, something with spaces ]

Maybe I didn't refactored your code correctly though, please have a look just to make sure. The command to run the tests is `go test`.

**Comment by hashhar** [comment]
I'll check it out by Saturday. Thanks for the refactoring.

Although I think we both have different ideas of how we would like to implement it.
The way I had written the code will never allow the second case you mentioned to pass. It always expects quotes when there are spaces.
But i think what you are aiming for is better. I'll try and implement that too.
