### ISSUE TITLE
Maintain the Windows release

### ISSUE THREAD

**Issue by hashhar** [laurent22/massren#21]
I would like to work actively on the Windows release.

I currently have my semester exams coming up and would like to maintain the Windows release after that from December.

**Comment by laurent22** [comment]
@hashhar, thanks for getting in touch.

That would be great if you could maintain the Windows version. Basically, what's needed is to see if it builds and maybe run `go test` to see if they all pass.

Once it's built, you can upload the version in the [release page](https://github.com/laurent22/massren/releases).

I've added you as a collaborator on the project. Please let me know if you have any question.

**Comment by hashhar** [comment]
Thanks a lot for this. I'll ask you things once I go through the code.

**Comment by hashhar** [comment]
I got the source through `go get github.com/laurent22/massren`
I got it to build successfully but haven't tried running it (yet). (Baby steps here)

I wanted to ask you about the development process.

- What files are created and where once I run `go build`?
- Should I build it outside the repo or in a separate branch?
- Do I have to make any changes to the other user directories that got created? Or is the project self contained within the massren repository?

**Comment by hashhar** [comment]
What do you expect the `/deploy/win-386.bat` to accomplish?
It looks wrong somehow.

Looking at the Linux deploy script `_posix.sh` I can say:
- Build the program
- Package the generated executable into a tarball inside `releases`
- Create an installation script in `install`
- The script will make sure not to overwrite the older archive and download the release matching the version we just built
- Untar the downloaded archive and execute the install script
- Move the final binary executable to /usr/bin
- Remove the executable we created in the first step

**Comment by laurent22** [comment]
> What files are created and where once I run go build?

Just one file is generated when you run `go build`, the executable. You can name it by running `go build -o massren.exe`

> Should I build it outside the repo or in a separate branch?

Please always build from the master branch.

> Do I have to make any changes to the other user directories that got created? Or is the project self contained within the massren repository?

All the project is in the massren repository. There's also a homebrew-massren repo for Homebrew but it's not needed for the Windows version.

> What do you expect the /deploy/win-386.bat to accomplish?

That was the script I used before to build it with Cygwin, please disregard it (especially since I see it includes hard coded paths to stuff on my machine)

> Looking at the Linux deploy script _posix.sh I can say:

This script automates many things for OSX and Linux, but for Windows it's actually simpler. All that is needed is to:

- Build the executable with `go build -o massren.exe`
- Zip the file `massren.exe` into a file called `massren.win-386.zip`

And upload it to the release section on Github. Maybe that it would be useful to create some .bat file to automate this, but basically with Go it's quite straightforward since it creates a static executable.

**Comment by laurent22** [comment]
The official releases normally are based on tags from the master branch. It's fine to create one from a different branch, but what would it be for? Is it for some kind of beta version?

**Comment by hashhar** [comment]
I completely forgot I had asked this. I am now building on the master branch and have a separate branch to use as a scratch space.

I think I'll close this issue now.

**Comment by hashhar** [comment]
I can write a script for that. But I'm not sure if I'd be able to get it done in Command Prompt. It's easier in PowerShell.

**Comment by kpym** [comment]
I have comiled the last version 1.5.4 for windows. When I use it it works, but when I run the `go test` it fails with this message : 
```
# massren
.\main_test.go:253:5: Error call has possible formatting directive %s
.\main_test.go:338:4: Errorf format %b has arg testCase.hasError of wrong type bool
FAIL    massren [build failed]
```
So my questions are : 
- How this test errors should be corrected ?
- How can I upload `massren.win-386.zip` to the release page ?
