### ISSUE TITLE
-n and -v give very similar (read: the same) output

### ISSUE THREAD

**Issue by hashhar** [laurent22/massren#23]
![snip_20151118000427](https://cloud.githubusercontent.com/assets/10473142/11220853/fec34bfa-8d87-11e5-994a-78339538b5b1.png)

Both -n and -v options give similarly formatted output... I think we should add a header like: "Operations that would have been performed:" to the -n option.

**Comment by laurent22** [comment]
I've probably implemented it that way based on the output of commands like `rsync`, which also don't indicate that they are running in dry run mode:

	$ rsync -aP -n temp/ temp.test/
	sending incremental file list
	created directory temp.test
	./
	1.txt
	2.txt
	3.txt

I think it makes sense because you want to know exactly what would happen in dry-run mode, including what output would be generated (for example, if it's parsed by other tools). If we add a header the dry-run and regular mode will have different outputs and that could be a problem. So unless there's a good reason for it, I'd rather leave it as it is.

**Comment by hashhar** [comment]
Makes sense.
